//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinerRandevuSistEfrDBFirstProc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hastalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hastalar()
        {
            this.Randevulars = new HashSet<Randevular>();
        }
    
        public int hastano { get; set; }
        public string hastaAdi { get; set; }
        public string hastaCinsi { get; set; }
        public Nullable<int> hastaYas { get; set; }
        public string Ebeveyn { get; set; }
        public string Tel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Randevular> Randevulars { get; set; }
    }
}
