//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinerRandevuSistEfrDBFirstProc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevular
    {
        public int randevuNo { get; set; }
        public Nullable<int> hastano { get; set; }
        public Nullable<int> calisanNo { get; set; }
        public Nullable<int> islemNo { get; set; }
        public Nullable<System.DateTime> RandevuDate { get; set; }
    
        public virtual Calisanlar Calisanlar { get; set; }
        public virtual Hastalar Hastalar { get; set; }
        public virtual Islemler Islemler { get; set; }
    }
}
