//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinerRandevuSistEfrDBFirstProc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VeterinerRandevuEntities : DbContext
    {
        public VeterinerRandevuEntities()
            : base("name=VeterinerRandevuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calisanlar> Calisanlars { get; set; }
        public virtual DbSet<Hastalar> Hastalars { get; set; }
        public virtual DbSet<Islemler> Islemlers { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<Randevular> Randevulars { get; set; }
    
        public virtual int CalisanEkle(string calisanAdi, string statü)
        {
            var calisanAdiParameter = calisanAdi != null ?
                new ObjectParameter("calisanAdi", calisanAdi) :
                new ObjectParameter("calisanAdi", typeof(string));
    
            var statüParameter = statü != null ?
                new ObjectParameter("statü", statü) :
                new ObjectParameter("statü", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalisanEkle", calisanAdiParameter, statüParameter);
        }
    
        public virtual int CalisanGuncelle(Nullable<int> calisanNo, string calisanAdi, string statu)
        {
            var calisanNoParameter = calisanNo.HasValue ?
                new ObjectParameter("calisanNo", calisanNo) :
                new ObjectParameter("calisanNo", typeof(int));
    
            var calisanAdiParameter = calisanAdi != null ?
                new ObjectParameter("calisanAdi", calisanAdi) :
                new ObjectParameter("calisanAdi", typeof(string));
    
            var statuParameter = statu != null ?
                new ObjectParameter("statu", statu) :
                new ObjectParameter("statu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalisanGuncelle", calisanNoParameter, calisanAdiParameter, statuParameter);
        }
    
        public virtual ObjectResult<CalisanListele_Result> CalisanListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalisanListele_Result>("CalisanListele");
        }
    
        public virtual int CalisanSil(Nullable<int> calisanNo)
        {
            var calisanNoParameter = calisanNo.HasValue ?
                new ObjectParameter("calisanNo", calisanNo) :
                new ObjectParameter("calisanNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalisanSil", calisanNoParameter);
        }
    
        public virtual int HastaEkle(string hastaAdi, string hastaCinsi, Nullable<int> hastaYas, string ebeveyn, string telefon)
        {
            var hastaAdiParameter = hastaAdi != null ?
                new ObjectParameter("hastaAdi", hastaAdi) :
                new ObjectParameter("hastaAdi", typeof(string));
    
            var hastaCinsiParameter = hastaCinsi != null ?
                new ObjectParameter("hastaCinsi", hastaCinsi) :
                new ObjectParameter("hastaCinsi", typeof(string));
    
            var hastaYasParameter = hastaYas.HasValue ?
                new ObjectParameter("hastaYas", hastaYas) :
                new ObjectParameter("hastaYas", typeof(int));
    
            var ebeveynParameter = ebeveyn != null ?
                new ObjectParameter("ebeveyn", ebeveyn) :
                new ObjectParameter("ebeveyn", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("telefon", telefon) :
                new ObjectParameter("telefon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HastaEkle", hastaAdiParameter, hastaCinsiParameter, hastaYasParameter, ebeveynParameter, telefonParameter);
        }
    
        public virtual int HastaGuncelle(Nullable<int> hastano, string hastaAdi, string hastaCinsi, Nullable<int> hastaYas, string ebeveyn, string telefon)
        {
            var hastanoParameter = hastano.HasValue ?
                new ObjectParameter("hastano", hastano) :
                new ObjectParameter("hastano", typeof(int));
    
            var hastaAdiParameter = hastaAdi != null ?
                new ObjectParameter("hastaAdi", hastaAdi) :
                new ObjectParameter("hastaAdi", typeof(string));
    
            var hastaCinsiParameter = hastaCinsi != null ?
                new ObjectParameter("hastaCinsi", hastaCinsi) :
                new ObjectParameter("hastaCinsi", typeof(string));
    
            var hastaYasParameter = hastaYas.HasValue ?
                new ObjectParameter("hastaYas", hastaYas) :
                new ObjectParameter("hastaYas", typeof(int));
    
            var ebeveynParameter = ebeveyn != null ?
                new ObjectParameter("ebeveyn", ebeveyn) :
                new ObjectParameter("ebeveyn", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("telefon", telefon) :
                new ObjectParameter("telefon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HastaGuncelle", hastanoParameter, hastaAdiParameter, hastaCinsiParameter, hastaYasParameter, ebeveynParameter, telefonParameter);
        }
    
        public virtual ObjectResult<HastaListele_Result> HastaListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HastaListele_Result>("HastaListele");
        }
    
        public virtual int HastaSil(Nullable<int> hastano)
        {
            var hastanoParameter = hastano.HasValue ?
                new ObjectParameter("hastano", hastano) :
                new ObjectParameter("hastano", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HastaSil", hastanoParameter);
        }
    
        public virtual int IslemEkle(string islemAd, Nullable<decimal> islemUcret)
        {
            var islemAdParameter = islemAd != null ?
                new ObjectParameter("islemAd", islemAd) :
                new ObjectParameter("islemAd", typeof(string));
    
            var islemUcretParameter = islemUcret.HasValue ?
                new ObjectParameter("islemUcret", islemUcret) :
                new ObjectParameter("islemUcret", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IslemEkle", islemAdParameter, islemUcretParameter);
        }
    
        public virtual int IslemGuncelle(Nullable<int> islemno, string islemAd, Nullable<decimal> islemUcret)
        {
            var islemnoParameter = islemno.HasValue ?
                new ObjectParameter("islemno", islemno) :
                new ObjectParameter("islemno", typeof(int));
    
            var islemAdParameter = islemAd != null ?
                new ObjectParameter("islemAd", islemAd) :
                new ObjectParameter("islemAd", typeof(string));
    
            var islemUcretParameter = islemUcret.HasValue ?
                new ObjectParameter("islemUcret", islemUcret) :
                new ObjectParameter("islemUcret", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IslemGuncelle", islemnoParameter, islemAdParameter, islemUcretParameter);
        }
    
        public virtual ObjectResult<IslemListele_Result> IslemListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IslemListele_Result>("IslemListele");
        }
    
        public virtual int IslemSil(Nullable<int> islemno)
        {
            var islemnoParameter = islemno.HasValue ?
                new ObjectParameter("islemno", islemno) :
                new ObjectParameter("islemno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IslemSil", islemnoParameter);
        }
    
        public virtual int KullaniciEkle(string kullaniciAd, string sifre)
        {
            var kullaniciAdParameter = kullaniciAd != null ?
                new ObjectParameter("kullaniciAd", kullaniciAd) :
                new ObjectParameter("kullaniciAd", typeof(string));
    
            var sifreParameter = sifre != null ?
                new ObjectParameter("sifre", sifre) :
                new ObjectParameter("sifre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KullaniciEkle", kullaniciAdParameter, sifreParameter);
        }
    
        public virtual int KullaniciGuncelle(Nullable<int> kullaniciNo, string kullaniciAd, string sifre)
        {
            var kullaniciNoParameter = kullaniciNo.HasValue ?
                new ObjectParameter("kullaniciNo", kullaniciNo) :
                new ObjectParameter("kullaniciNo", typeof(int));
    
            var kullaniciAdParameter = kullaniciAd != null ?
                new ObjectParameter("kullaniciAd", kullaniciAd) :
                new ObjectParameter("kullaniciAd", typeof(string));
    
            var sifreParameter = sifre != null ?
                new ObjectParameter("sifre", sifre) :
                new ObjectParameter("sifre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KullaniciGuncelle", kullaniciNoParameter, kullaniciAdParameter, sifreParameter);
        }
    
        public virtual ObjectResult<KullaniciListele_Result> KullaniciListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KullaniciListele_Result>("KullaniciListele");
        }
    
        public virtual int KullaniciSil(Nullable<int> kullaniciNo)
        {
            var kullaniciNoParameter = kullaniciNo.HasValue ?
                new ObjectParameter("kullaniciNo", kullaniciNo) :
                new ObjectParameter("kullaniciNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KullaniciSil", kullaniciNoParameter);
        }
    
        public virtual int RandevuEkle(Nullable<int> hastano, Nullable<int> calisanNo, Nullable<int> islemNo, Nullable<System.DateTime> randevudate)
        {
            var hastanoParameter = hastano.HasValue ?
                new ObjectParameter("hastano", hastano) :
                new ObjectParameter("hastano", typeof(int));
    
            var calisanNoParameter = calisanNo.HasValue ?
                new ObjectParameter("calisanNo", calisanNo) :
                new ObjectParameter("calisanNo", typeof(int));
    
            var islemNoParameter = islemNo.HasValue ?
                new ObjectParameter("islemNo", islemNo) :
                new ObjectParameter("islemNo", typeof(int));
    
            var randevudateParameter = randevudate.HasValue ?
                new ObjectParameter("randevudate", randevudate) :
                new ObjectParameter("randevudate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RandevuEkle", hastanoParameter, calisanNoParameter, islemNoParameter, randevudateParameter);
        }
    
        public virtual int RandevuGuncelle(Nullable<int> randevuno, Nullable<int> hastano, Nullable<int> calisanNo, Nullable<int> islemNo, Nullable<System.DateTime> randevudate)
        {
            var randevunoParameter = randevuno.HasValue ?
                new ObjectParameter("randevuno", randevuno) :
                new ObjectParameter("randevuno", typeof(int));
    
            var hastanoParameter = hastano.HasValue ?
                new ObjectParameter("hastano", hastano) :
                new ObjectParameter("hastano", typeof(int));
    
            var calisanNoParameter = calisanNo.HasValue ?
                new ObjectParameter("calisanNo", calisanNo) :
                new ObjectParameter("calisanNo", typeof(int));
    
            var islemNoParameter = islemNo.HasValue ?
                new ObjectParameter("islemNo", islemNo) :
                new ObjectParameter("islemNo", typeof(int));
    
            var randevudateParameter = randevudate.HasValue ?
                new ObjectParameter("randevudate", randevudate) :
                new ObjectParameter("randevudate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RandevuGuncelle", randevunoParameter, hastanoParameter, calisanNoParameter, islemNoParameter, randevudateParameter);
        }
    
        public virtual ObjectResult<RandevuListele_Result> RandevuListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RandevuListele_Result>("RandevuListele");
        }
    
        public virtual int RandevuSil(Nullable<int> randevuno)
        {
            var randevunoParameter = randevuno.HasValue ?
                new ObjectParameter("randevuno", randevuno) :
                new ObjectParameter("randevuno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RandevuSil", randevunoParameter);
        }
    
        public virtual ObjectResult<KullaniciAra_Result> KullaniciAra(string kullaniciAd)
        {
            var kullaniciAdParameter = kullaniciAd != null ?
                new ObjectParameter("kullaniciAd", kullaniciAd) :
                new ObjectParameter("kullaniciAd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KullaniciAra_Result>("KullaniciAra", kullaniciAdParameter);
        }
    
        public virtual ObjectResult<CalAdiAra_Result> CalAdiAra(string calisanAd)
        {
            var calisanAdParameter = calisanAd != null ?
                new ObjectParameter("calisanAd", calisanAd) :
                new ObjectParameter("calisanAd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalAdiAra_Result>("CalAdiAra", calisanAdParameter);
        }
    
        public virtual ObjectResult<CalStatAra_Result> CalStatAra(string statu)
        {
            var statuParameter = statu != null ?
                new ObjectParameter("statu", statu) :
                new ObjectParameter("statu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalStatAra_Result>("CalStatAra", statuParameter);
        }
    
        public virtual ObjectResult<EbeveynTelAra_Result> EbeveynTelAra(string telefon)
        {
            var telefonParameter = telefon != null ?
                new ObjectParameter("telefon", telefon) :
                new ObjectParameter("telefon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EbeveynTelAra_Result>("EbeveynTelAra", telefonParameter);
        }
    
        public virtual ObjectResult<HastaAdAra_Result> HastaAdAra(string hastaAd)
        {
            var hastaAdParameter = hastaAd != null ?
                new ObjectParameter("hastaAd", hastaAd) :
                new ObjectParameter("hastaAd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HastaAdAra_Result>("HastaAdAra", hastaAdParameter);
        }
    
        public virtual ObjectResult<HastaCinsAra_Result> HastaCinsAra(string hastacins)
        {
            var hastacinsParameter = hastacins != null ?
                new ObjectParameter("hastacins", hastacins) :
                new ObjectParameter("hastacins", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HastaCinsAra_Result>("HastaCinsAra", hastacinsParameter);
        }
    
        public virtual ObjectResult<HastaEbeveynAra_Result> HastaEbeveynAra(string ebeveyn)
        {
            var ebeveynParameter = ebeveyn != null ?
                new ObjectParameter("ebeveyn", ebeveyn) :
                new ObjectParameter("ebeveyn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HastaEbeveynAra_Result>("HastaEbeveynAra", ebeveynParameter);
        }
    
        public virtual ObjectResult<HastaYasAra_Result> HastaYasAra(Nullable<int> hastayas)
        {
            var hastayasParameter = hastayas.HasValue ?
                new ObjectParameter("hastayas", hastayas) :
                new ObjectParameter("hastayas", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HastaYasAra_Result>("HastaYasAra", hastayasParameter);
        }
    
        public virtual ObjectResult<IslemAdAra_Result> IslemAdAra(string islemAd)
        {
            var islemAdParameter = islemAd != null ?
                new ObjectParameter("islemAd", islemAd) :
                new ObjectParameter("islemAd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IslemAdAra_Result>("IslemAdAra", islemAdParameter);
        }
    
        public virtual ObjectResult<HastUygIslemler_Result> HastUygIslemler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HastUygIslemler_Result>("HastUygIslemler");
        }
    
        public virtual ObjectResult<RandFatura_Result> RandFatura()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RandFatura_Result>("RandFatura");
        }
    
        public virtual ObjectResult<YilllaraGoreKazanclari_Result> YilllaraGoreKazanclari()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YilllaraGoreKazanclari_Result>("YilllaraGoreKazanclari");
        }
    
        public virtual ObjectResult<YilllaraGoreYapIslemler_Result> YilllaraGoreYapIslemler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YilllaraGoreYapIslemler_Result>("YilllaraGoreYapIslemler");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int sp_alterdiagram1(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram1", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram1(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram1", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram1(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram1", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition1_Result> sp_helpdiagramdefinition1(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition1_Result>("sp_helpdiagramdefinition1", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams1_Result> sp_helpdiagrams1(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams1_Result>("sp_helpdiagrams1", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram1(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram1", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams1");
        }
    
        public virtual ObjectResult<Faturalar_Result> Faturalar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Faturalar_Result>("Faturalar");
        }
    }
}
